# Generated by Django 4.1.6 on 2023-02-13 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_alter_trait_pet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="pet",
            new_name="pets",
        ),
    ]
